apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eostrovatikova-namespace
images:
  - name: nginx
    newName: nginx
    newTag: 1.23.2-alpine
  - name: admindevopsfinal/devopsimage
    newTag: latest

resources:
- ../../base
- namespace.yaml
- ingress.yaml
- certificate.yaml